#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.name=defaultDataSource
#spring.datasource.url=jdbc:mysql://localhost:3306/blue?serverTimezone=UTC
#spring.datasource.username=***
#spring.datasource.password=***
#server.port=8080
server:
  port: 8888
spring:
  application:
    name: blog
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: always
  redis:
    host: localhost
    port: 6379
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 1
#        time-between-eviction-runs: 10s

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_
